name: Aggiorna News

on:
  schedule:
    - cron: '*/10 * * * *'  # ogni 10 minuti
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install node-fetch@2 xml2js

      - name: Run aggregator
        run: |
          node aggregator.js

      - name: Commit updated news.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add news.json
          git commit -m "Aggiorna news $(date -u +"%Y-%m-%dT%H:%M:%SZ")" || echo "No changes"
          git push
