# .github/workflows/clean-news-json.yml
name: Clean news.json

# Permessi per consentire il push automatico
defaults:
  run:
    shell: bash
permissions:
  contents: write

on:
  # Esecuzione manuale via GitHub UI
  workflow_dispatch:
  # Trigger su modifica di news.json
  push:
    paths:
      - news.json
  # Esecuzione giornaliera a mezzanotte UTC
  schedule:
    - cron: '0 0 * * *'

jobs:
  clean:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Usa il token GITHUB_TOKEN per push automatico
          persist-credentials: true

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Clean HTML/CSS remnants from news.json
        run: |
          jq '
            # Definisce la funzione clean per pulire stringhe
            def clean:
              if type == "string" then
                # Rimuovi blocchi <style> e <script>
                gsub("<style[\s\S]*?</style>"; "") |
                gsub("<script[\s\S]*?</script>"; "") |
                # Rimuovi tag HTML
                gsub("<[^>]+>"; "") |
                # Rimuovi commenti HTML
                gsub("<!--[^>]*-->"; "") |
                # Rimuovi blocchi CSS residui .classe{...}
                gsub("\\.?[A-Za-z0-9_\\-]+\\s*\\{[^}]*\\}"; "") |
                # Rimuovi proprietà CSS prop:val;
                gsub("[A-Za-z\\-]+:[^;]+;"; "") |
                # Rimuovi entità HTML
                gsub("&nbsp;"; " ") |
                gsub("&[A-Za-z0-9#]+;"; "") |
                # Collassa whitespace
                gsub("\\s+"; " ") |
                # Trim spazi estremi
                sub("^\\s+"; "") |
                sub("\\s+$"; "")
              else
                .
              end;
            # Applica clean a ogni campo body
            (.categories? // .categorie?)?.items? |= map(.body |= clean)
          ' news.json > news.tmp.json
          mv news.tmp.json news.json

      - name: Commit & push cleaned JSON
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '🔄 Cleanup HTML/CSS residues from news.json'
          file_pattern: news.json
