# .github/workflows/clean-news-json.yml
name: Clean news.json

on:
  # Trigger su modifica di news.json
  push:
    paths:
      - news.json
  # Esecuzione periodica (giornaliera a mezzanotte UTC)
  schedule:
    - cron: '0 0 * * *'
  # Possibilità di esecuzione manuale da GitHub UI
  workflow_dispatch:

jobs:
  clean:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Clean HTML/CSS remnants from body fields
        run: |
          jq '
            # funzione di pulizia: solo su stringhe
            def clean:
              if type == "string" then
                gsub("<[^>]+>";"") |        
                gsub("<!--[^>]*-->";"") |
                gsub("&nbsp;";" ") |
                gsub("&[a-zA-Z0-9#]+;";"") |
                gsub("\\s+";" ") |
                sub("^\\s+"; "") |
                sub("\\s+$"; "")
              else
                .
              end;

            # Applica clean a .body in categories o categorie
            (
              (.categories? // .categorie?)
              |= map(
                   .items |= map(
                     .body |= clean
                   )
                 )
            )
          ' news.json > news.cleaned.json
          mv news.cleaned.json news.json

      - name: Commit & push cleaned news.json
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '🔄 Cleanup HTML/CSS residues from news.json'
          file_pattern: news.json
