# .github/workflows/clean-news-json.yml
name: Clean news.json

defaults:
  run:
    shell: bash

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    paths:
      - news.json
  schedule:
    - cron: '0 0 * * *'

jobs:
  clean:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Clean HTML/CSS remnants from news.json
        run: |
          jq 'def clean:
                if type=="string" then
                  gsub("<style[\\s\\S]*?</style>";"") |
                  gsub("<script[\\s\\S]*?</script>";"") |
                  gsub("<[^>]+>";"") |
                  gsub("<!--[^>]*-->";"") |
                  gsub("\\.?[A-Za-z0-9_\\-]+[[:space:]]*\\{[^}]*\\}";"") |
                  gsub("[A-Za-z\\-]+:[^;]+;";"") |
                  gsub("&nbsp;";" ") |
                  gsub("&[^;]+;";"") |
                  gsub("[[:space:]]+";" ") |
                  sub("^[[:space:]]+";"") |
                  sub("[[:space:]]+$";"")
                else
                  .
                end;
            (.categories?//.categorie?)?.items? |= map(.body |= clean)' news.json > news.tmp.json
          mv news.tmp.json news.json

      - name: Commit & push cleaned JSON
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '🔄 Cleanup HTML/CSS residues from news.json'
          file_pattern: news.json
