# .github/workflows/clean-news-json.yml
name: Clean news.json

# Permessi per consentire il push automatico
dependabot:
permissions:
  contents: write

on:
  # Esecuzione manuale
  workflow_dispatch:
  # Trigger su modifica di news.json
  push:
    paths:
      - news.json
  # Esecuzione giornaliera a mezzanotte UTC
  schedule:
    - cron: '0 0 * * *'

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # abilita GITHUB_TOKEN per i push

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Clean HTML/CSS remnants from news.json
        run: |
          jq '
            # funzione clean: opera solo su stringhe
            def clean:
              if type == "string" then
                # rimuovi <style> e <script> e i loro contenuti
                gsub("<style[\s\S]*?</style>"; "") |
                gsub("<script[\s\S]*?</script>"; "") |
                # rimuovi tutti i tag HTML
                gsub("<[^>]+>"; "") |
                # rimuovi commenti HTML
                gsub("<!--[^>]*-->"; "") |
                # rimuovi blocchi CSS residui: .classe{...}
                gsub("\\.?[A-Za-z0-9_\\-]+\\s*\\{[^}]*\\}"; "") |
                # rimuovi proprietà CSS: prop:val;
                gsub("[A-Za-z\\-]+:[^;]+;"; "") |
                # decodifica &nbsp; e rimuovi altre entità
                gsub("&nbsp;"; " ") |
                gsub("&[A-Za-z0-9#]+;"; "") |
                # collassa whitespace multipli in singolo spazio
                gsub("\\s+"; " ") |
                # trim spazi iniziali/finali
                sub("^\\s+"; "") |
                sub("\\s+$"; "")
              else
                .
              end;
            # applica clean a ogni body
            (.categories? // .categorie?)?.items? |= map(.body |= clean)
          ' news.json > news.tmp.json
          mv news.tmp.json news.json

      - name: Commit & push cleaned JSON
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '🔄 Cleanup HTML/CSS residues from news.json'
          file_pattern: news.json
