# .github/workflows/clean-news-json.yml
name: Clean news.json

on:
  push:
    paths:
      - news.json
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ripulisci body di news.json
        run: |
          jq '
            .categories[].items[].body |=
              # 1) Rimuovi tutti i tag HTML
              gsub("<[^>]+>";"") |
              # 2) Sostituisci &nbsp; con spazio
              gsub("&nbsp;";" ") |
              # 3) Rimuovi qualsiasi altra entità HTML
              gsub("&[a-zA-Z0-9]+;";"") |
              # 4) Collassa newline e spazi multipli in uno spazio
              gsub("\\s+";" ") |
              # 5) Trim spazi iniziali e finali
              sub("^\\s+"; "") | sub("\\s+$"; "")
          ' news.json > news.cleaned.json
          mv news.cleaned.json news.json

      - name: Commit & Push cleaned JSON
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '🔄 Clean HTML & entities from news.json'
          file_pattern: news.json
