name: Clean news.json

on:
  # Esegue automaticamente quando news.json viene modificato
  push:
    paths:
      - news.json
  # Esegue su schedule giornaliero a mezzanotte UTC
  schedule:
    - cron: '0 0 * * *'
  # Permette l’esecuzione manuale via GitHub UI
  workflow_dispatch:

jobs:
  clean:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Clean HTML/CSS remnants from news.json body
        run: |
          jq '
            .categories[].items[].body |=
              # 1) Rimuovi tutti i tag HTML/CSS
              gsub("<[^>]+>";"") |
              # 2) Rimuovi residui di commenti HTML
              gsub("<!--[^>]*-->";"") |
              # 3) Sostituisci &nbsp; con spazio
              gsub("&nbsp;";" ") |
              # 4) Rimuovi qualunque altra entità HTML
              gsub("&[a-zA-Z0-9#]+;";"") |
              # 5) Collassa newline, tab e spazi multipli in uno spazio
              gsub("\\s+";" ") |
              # 6) Trim spazi iniziali/finali
              sub("^\\s+"; "") | sub("\\s+$"; "")
          ' news.json > news.cleaned.json
          mv news.cleaned.json news.json

      - name: Commit & Push cleaned JSON
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '🔄 Cleanup HTML/CSS residues from news.json'
          file_pattern: news.json
