# .github/workflows/clean-news-json.yml
name: Clean news.json

on:
  push:
    paths:
      - news.json
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  clean:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # usa GITHUB_TOKEN per i push

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Clean HTML/CSS remnants from body fields
        run: |
          jq '
            def clean:
              if type == "string" then
                gsub("<style[\\s\\S]*?</style>"; "") |
                gsub("<script[\\s\\S]*?</script>"; "") |
                gsub("<[^>]+>"; "") |
                gsub("<!--[^>]*-->"; "") |
                gsub("&nbsp;"; " ") |
                gsub("&[a-zA-Z0-9#]+;"; "") |
                gsub("\\s+"; " ") |
                sub("^\\s+"; "") |
                sub("\\s+$"; "")
              else . end;
            (
              (.categories? // .categorie?)
              |= map(
                   .items |= map(
                     .body |= clean
                   )
                 )
            )
          ' news.json > news.cleaned.json
          mv news.cleaned.json news.json

      - name: Commit & push cleaned news.json
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: '🔄 Cleanup HTML/CSS residues from news.json'
          file_pattern: news.json
