# .github/workflows/clean-news-json.yml
name: Clean news.json

# Permessi per consentire il push automatico
defaults:
  run:
    shell: bash
permissions:
  contents: write

on:
  # Esecuzione manuale via GitHub UI
  workflow_dispatch:
  # Trigger su modifica di news.json
  push:
    paths:
      - news.json
  # Esecuzione giornaliera a mezzanotte UTC
  schedule:
    - cron: '0 0 * * *'

jobs:
  clean:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Usa il GITHUB_TOKEN per le operazioni Git
          persist-credentials: true

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Clean HTML/CSS remnants from news.json
        run: |
          jq '
            # funzione clean: rimuove residui HTML/CSS da stringhe
            def clean:
              if type == "string" then
                # 1) Rimuovi blocchi <style>...</style> e <script>...</script>
                gsub("<style[\\s\\S]*?</style>"; "") |
                gsub("<script[\\s\\S]*?</script>"; "") |
                # 2) Rimuovi tutti i tag HTML
                gsub("<[^>]+>"; "") |
                # 3) Rimuovi commenti HTML
                gsub("<!--[^>]*-->"; "") |
                # 4) Rimuovi blocchi CSS residui come .class{...}
                gsub("\\.?[A-Za-z0-9_\\-]+\\s*\\{[^}]*\\}"; "") |
                # 5) Rimuovi proprietà CSS prop:value;
                gsub("[A-Za-z\\-]+:[^;]+;"; "") |
                # 6) Decodifica &nbsp; e rimuovi altre entità HTML
                gsub("&nbsp;"; " ") |
                gsub("&[A-Za-z0-9#]+;"; "") |
                # 7) Collassa whitespace multipli in uno spazio
                gsub("\\s+"; " ") |
                # 8) Trim spazi all'inizio e alla fine
                sub("^\\s+"; "") |
                sub("\\s+$"; "")
              else
                .
              end;
            # Applica clean a ogni campo body nelle categorie
            (.categories? // .categorie?)?.items? |= map(.body |= clean)
          ' news.json > news.tmp.json
          mv news.tmp.json news.json

      - name: Commit & push cleaned JSON
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '🔄 Cleanup HTML/CSS residues from news.json'
          file_pattern: news.json
