name: Aggiorna Stats CO2-Temp-Solare

permissions:
  contents: write   # abilita push tramite GITHUB_TOKEN

on:
  schedule:
    - cron: '0 08 * * *'    # ogni giorno alle 08:00 UTC
  workflow_dispatch:       # run manuale

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Genera stats_env_co2_solar.json
        run: node stats_env_co2_solar.js

      - name: Commit & Push changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add stats_env_co2_solar.json
          # crea commit anche se è solo touched_at
          git commit -m "🔄 Aggiorna stats_env_co2_solar.json" --allow-empty
          git push
